#!/usr/bin/expect -f
set timeout 60
set password "TimAdd#072082"
set server "102.218.215.253"
set user "root"

spawn scp -o StrictHostKeyChecking=no /workspace/sailingsa/deploy/apply_midmar_caitlin_helm.py ${user}@${server}:/tmp/apply_midmar_caitlin_helm.py
expect {
    -re "assword" { send "$password\r"; exp_continue }
    eof { }
}
wait

spawn ssh -o StrictHostKeyChecking=no ${user}@${server} {python3 /tmp/apply_midmar_caitlin_helm.py}
expect {
    -re "assword" { send "$password\r"; exp_continue }
    eof { }
}
wait
